"""empty message

Revision ID: 294079b5e1fe
Revises: 
Create Date: 2024-10-07 21:58:43.425855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294079b5e1fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('insert_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('client_pkey')),
    sa.UniqueConstraint('email', name=op.f('client_email_key')),
    sa.UniqueConstraint('id', name=op.f('client_id_key'))
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('insert_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('product_pkey'))
    )
    op.create_table('wishlist',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('insert_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('wishlist_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wishlist_pkey'))
    )
    op.create_table('wishlist_product',
    sa.Column('wishlist_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('wishlist_product_product_id_fkey')),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlist.id'], name=op.f('wishlist_product_wishlist_id_fkey')),
    sa.PrimaryKeyConstraint('wishlist_id', 'product_id', name=op.f('wishlist_product_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_product')
    op.drop_table('wishlist')
    op.drop_table('product')
    op.drop_table('client')
    # ### end Alembic commands ###
